name: docker-build
on: [push]
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v4.0.0
        with:
          file: Dockerfile-backend
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/musicparty-backend:latest
          push: true
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v4.0.0
        with:
          file: Dockerfile-frontend
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/musicparty-frontend:latest
          push: true
  music-api-servers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push neteaseapi
        uses: docker/build-push-action@v4.0.0
        with:
          file: Dockerfile-neteaseapi
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/musicparty-neteaseapi:latest
          push: true
      - name: Build and Push qqmusicapi
        uses: docker/build-push-action@v4.0.0
        with:
          file: Dockerfile-qqmusicapi
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/musicparty-qqmusicapi:latest
          push: true
